org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties (see https://fabricmc.net/develop)
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_api_version=0.161.0+26.3

# Mod Properties
version=2.11.5+26.3
group=dev.hexnowloading.dungeonnowloading
mod_id=dungeonnowloading
mod_name=Dungeon Now Loading
mod_author=Hexnowloading

# Dependencies
cca_version=8.1.0
# Modrinth version id of ForgeConfigAPIPort v26.3.1 (Fabric)
forgeconfigapiport_version=JpKvrr9J
